In [2]:
import pandas as pd
from sqlalchemy import create_engine

### weather

In [2]:
weather_data = pd.read_csv("./data_1/wether_.csv")

In [3]:
weather_data

,year,max_tempmax_month_5,max_tempmax_month_6,max_tempmax_month_7,max_tempmax_month_8,max_tempmax_month_9,max_tempmax_month_10,min_tempmax_month_5,min_tempmax_month_6,min_tempmax_month_7,...,mean_cloudcover_month_7,mean_cloudcover_month_8,mean_cloudcover_month_9,mean_cloudcover_month_10,std_cloudcover_month_5,std_cloudcover_month_6,std_cloudcover_month_7,std_cloudcover_month_8,std_cloudcover_month_9,std_cloudcover_month_10
0,2018,29.7,29.9,29.3,29.8,29.9,22.9,14.9,12.6,15.4,...,67.474194,48.309677,59.550000,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.175800
1,2020,27.4,29.9,30.1,32.8,30.7,21.8,7.6,11.0,17.6,...,60.516129,47.380645,49.096667,85.480645,20.389051,15.075481,20.282194,19.390555,29.610814,13.894901
2,2021,23.2,32.4,34.1,29.6,25.1,19.5,9.4,15.4,19.9,...,54.719355,59.800000,65.043333,48.183871,25.594998,21.686078,27.606586,23.888658,26.689152,30.516139
3,2022,29.3,33.9,33.4,31.4,22.9,20.7,14.7,19.1,17.8,...,57.148387,58.135484,82.520000,69.633333,20.486173,24.235914,22.721163,27.867000,19.940729,24.506224
4,2023,26.4,29.2,32.2,34.9,28.9,25.4,8.9,11.4,17.9,...,61.551613,46.777419,42.996667,70.322581,28.547902,25.913016,23.104485,21.398858,31.044867,16.965783
5,2024,26.8,32.8,35.9,32.9,29.9,22.6,14.4,16.2,16.2,...,56.635484,43.606452,53.983333,61.748387,24.192672,21.986699,22.469365,27.514880,35.865708,33.080930

In [10]:
patterns = 'max_t|min_t|max_h|min_h|max_p|min_p|max_c|min_c'

df = weather_data.drop(weather_data.filter(regex=patterns).columns, axis=1)
df

,year,mean_tempmax_month_5,mean_tempmax_month_6,mean_tempmax_month_7,mean_tempmax_month_8,mean_tempmax_month_9,mean_tempmax_month_10,std_tempmax_month_5,std_tempmax_month_6,std_tempmax_month_7,...,mean_cloudcover_month_7,mean_cloudcover_month_8,mean_cloudcover_month_9,mean_cloudcover_month_10,std_cloudcover_month_5,std_cloudcover_month_6,std_cloudcover_month_7,std_cloudcover_month_8,std_cloudcover_month_9,std_cloudcover_month_10
0,2018,23.019355,23.656667,24.283871,26.403226,21.266667,16.103226,4.256244,4.093197,3.147708,...,67.474194,48.309677,59.550000,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.175800
1,2020,16.180645,23.646667,24.551613,26.777419,22.913333,15.061290,4.130490,4.356029,3.286424,...,60.516129,47.380645,49.096667,85.480645,20.389051,15.075481,20.282194,19.390555,29.610814,13.894901
2,2021,18.309677,24.133333,27.345161,23.096774,17.933333,13.383871,3.422801,4.429473,3.975998,...,54.719355,59.800000,65.043333,48.183871,25.594998,21.686078,27.606586,23.888658,26.689152,30.516139
3,2022,20.583871,26.250000,25.561290,25.935484,16.720000,16.022222,3.191039,4.022759,4.311201,...,57.148387,58.135484,82.520000,69.633333,20.486173,24.235914,22.721163,27.867000,19.940729,24.506224
4,2023,20.054839,22.646667,25.941935,28.109677,24.363333,16.864516,4.125113,3.956813,2.709831,...,61.551613,46.777419,42.996667,70.322581,28.547902,25.913016,23.104485,21.398858,31.044867,16.965783
5,2024,21.606452,25.203333,27.948387,28.003226,23.816667,14.141935,3.761111,3.750079,4.872431,...,56.635484,43.606452,53.983333,61.748387,24.192672,21.986699,22.469365,27.514880,35.865708,33.080930

In [11]:
list(df.columns)

['year',
 'mean_tempmax_month_5',
 'mean_tempmax_month_6',
 'mean_tempmax_month_7',
 'mean_tempmax_month_8',
 'mean_tempmax_month_9',
 'mean_tempmax_month_10',
 'std_tempmax_month_5',
 'std_tempmax_month_6',
 'std_tempmax_month_7',
 'std_tempmax_month_8',
 'std_tempmax_month_9',
 'std_tempmax_month_10',
 'mean_tempmin_month_5',
 'mean_tempmin_month_6',
 'mean_tempmin_month_7',
 'mean_tempmin_month_8',
 'mean_tempmin_month_9',
 'mean_tempmin_month_10',
 'std_tempmin_month_5',
 'std_tempmin_month_6',
 'std_tempmin_month_7',
 'std_tempmin_month_8',
 'std_tempmin_month_9',
 'std_tempmin_month_10',
 'mean_temp_month_5',
 'mean_temp_month_6',
 'mean_temp_month_7',
 'mean_temp_month_8',
 'mean_temp_month_9',
 'mean_temp_month_10',
 'std_temp_month_5',
 'std_temp_month_6',
 'std_temp_month_7',
 'std_temp_month_8',
 'std_temp_month_9',
 'std_temp_month_10',
 'mean_humidity_month_5',
 'mean_humidity_month_6',
 'mean_humidity_month_7',
 'mean_humidity_month_8',
 'mean_humidity_month_9',
 'mean_humidity_month_10',
 'std_humidity_month_5',
 'std_humidity_month_6',
 'std_humidity_month_7',
 'std_humidity_month_8',
 'std_humidity_month_9',
 'std_humidity_month_10',
 'mean_precip_month_5',
 'mean_precip_month_6',
 'mean_precip_month_7',
 'mean_precip_month_8',
 'mean_precip_month_9',
 'mean_precip_month_10',
 'std_precip_month_5',
 'std_precip_month_6',
 'std_precip_month_7',
 'std_precip_month_8',
 'std_precip_month_9',
 'std_precip_month_10',
 'mean_cloudcover_month_5',
 'mean_cloudcover_month_6',
 'mean_cloudcover_month_7',
 'mean_cloudcover_month_8',
 'mean_cloudcover_month_9',
 'mean_cloudcover_month_10',
 'std_cloudcover_month_5',
 'std_cloudcover_month_6',
 'std_cloudcover_month_7',
 'std_cloudcover_month_8',
 'std_cloudcover_month_9',
 'std_cloudcover_month_10']

In [12]:
len(list(df.columns))

73

In [13]:
df["location"] = "Ternopil,Uk"

In [14]:
df

,year,mean_tempmax_month_5,mean_tempmax_month_6,mean_tempmax_month_7,mean_tempmax_month_8,mean_tempmax_month_9,mean_tempmax_month_10,std_tempmax_month_5,std_tempmax_month_6,std_tempmax_month_7,...,mean_cloudcover_month_8,mean_cloudcover_month_9,mean_cloudcover_month_10,std_cloudcover_month_5,std_cloudcover_month_6,std_cloudcover_month_7,std_cloudcover_month_8,std_cloudcover_month_9,std_cloudcover_month_10,location
0,2018,23.019355,23.656667,24.283871,26.403226,21.266667,16.103226,4.256244,4.093197,3.147708,...,48.309677,59.550000,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.175800,"Ternopil,Uk"
1,2020,16.180645,23.646667,24.551613,26.777419,22.913333,15.061290,4.130490,4.356029,3.286424,...,47.380645,49.096667,85.480645,20.389051,15.075481,20.282194,19.390555,29.610814,13.894901,"Ternopil,Uk"
2,2021,18.309677,24.133333,27.345161,23.096774,17.933333,13.383871,3.422801,4.429473,3.975998,...,59.800000,65.043333,48.183871,25.594998,21.686078,27.606586,23.888658,26.689152,30.516139,"Ternopil,Uk"
3,2022,20.583871,26.250000,25.561290,25.935484,16.720000,16.022222,3.191039,4.022759,4.311201,...,58.135484,82.520000,69.633333,20.486173,24.235914,22.721163,27.867000,19.940729,24.506224,"Ternopil,Uk"
4,2023,20.054839,22.646667,25.941935,28.109677,24.363333,16.864516,4.125113,3.956813,2.709831,...,46.777419,42.996667,70.322581,28.547902,25.913016,23.104485,21.398858,31.044867,16.965783,"Ternopil,Uk"
5,2024,21.606452,25.203333,27.948387,28.003226,23.816667,14.141935,3.761111,3.750079,4.872431,...,43.606452,53.983333,61.748387,24.192672,21.986699,22.469365,27.514880,35.865708,33.080930,"Ternopil,Uk"

In [ ]:
# df.to_csv("./data_1/weather_.csv")

In [17]:
engine = create_engine(
    "postgresql://postgres:postgress@127.0.0.1:5432/postgres"
)

In [20]:
df.to_sql("weather_data", engine)

6

### guideline

In [3]:
guideline = pd.read_csv("./data_1/Fertilizers_data/guideline.csv")

In [4]:
guideline.columns

Index(['Довга назва елементу', 'Коротка назва елементу', 'Рівень вмісту',
       'Мінімальне значення', 'Максимальне значення', 'Код кольору'],
      dtype='object')

In [9]:
# guideline_ = guideline.drop(columns=["Код кольору"])
guideline_ = guideline.rename(
    columns={
        'Довга назва елементу' : "long_elem_name", 
        "Коротка назва елементу" : "short_elem_name",
        'Рівень вмісту' : "content_level",
        'Мінімальне значення' : "min_elem_value", 
        'Максимальне значення' : "max_elem_value",
        "Код кольору" : "color"
    }
)

guideline_["content_level"] = guideline_["content_level"].replace(
    {
        "Дуже низький" : "Very low",
        "Низький" : " Low",
        "Середній" : "Medium", 
        "Високий" : "High", 
        "Дуже високий" : "Very high"
    }
)

guideline_

,long_elem_name,short_elem_name,content_level,min_elem_value,max_elem_value,color
0,pH,pH,Very low,0.00,5.3,#ff0000
1,pH,pH,Low,5.31,6.2,#ff9933
2,pH,pH,Medium,6.21,7.0,#00FF00
3,pH,pH,High,7.01,7.4,#006600
4,pH,pH,Very high,7.41,14.0,#3333FF
...,...,...,...,...,...,...
70,Molybdenum,Mo,Very low,0.00,0.6,#ff0000
71,Molybdenum,Mo,Low,0.61,0.9,#ff9933
72,Molybdenum,Mo,Medium,0.91,2.0,#00FF00
73,Molybdenum,Mo,High,2.01,3.0,#006600
74,Molybdenum,Mo,Very high,3.01,999.0,#3333FF

In [11]:
engine = create_engine(
    "postgresql://postgres:postgress@127.0.0.1:5432/postgres"
)

In [12]:
guideline_.to_sql("elements_guideline", engine)

75

### Nutritients

In [3]:
crops_nutrients = {
    # кукурудза в кг на 1 тонну \ г на 1 тонну
    "Crop_34": {
            "N": 20,
            "P2O5": 9,
            "K2O": 25,
            "MgO": 8,
            "CaO": 6,
            "S": 2,
            "Fe": 224,
            "Zn": 40,
            "Mn": 36,
            "B": 25,
            "Cu": 11,
            "Mo": 1
    },
    #Сонях 
    "Crop_41": {
            "N": 37,
            "P2O5": 25,
            "K2O": 110,
            "MgO": 20,
            "CaO": 60,
            "Fe": 209,
            "Zn": 99,
            "Mn": 118,
            "B": 113,
            "Cu": 17,
    } ,   
# Ріпак
    "Crop_45": {
            "N": 32.8,
            "P2O5": 16.4,
            "K2O": 41.8,
            "MgO": 8.7,
            "CaO": 42.0,
            "S": 17.3,
            "Fe": 1123,
            "Zn": 100,
            "Mn": 95,
            "B": 0,
            "Cu": 17,
            "Mo": 0
        },
# Соя
    "Crop_174": {
            "N": 146,
            "P2O5": 25,
            "K2O": 53,
            "MgO": 22,
            "CaO": 28,
            "S": 5,
            "Fe": 476,
            "Zn": 104,
            "Mn": 123,
            "B": 55,
            "Cu": 41,
            "Mo": 13
        },
}

In [11]:
nutritient_df = pd.DataFrame.from_dict(crops_nutrients, orient="index")
nutritient_df = nutritient_df.fillna(0)

In [12]:
nutritient_df

              N  P2O5    K2O   MgO   CaO     S    Fe   Zn   Mn    B  Cu    Mo
Crop_34    20.0   9.0   25.0   8.0   6.0   2.0   224   40   36   25  11   1.0
Crop_41    37.0  25.0  110.0  20.0  60.0   0.0   209   99  118  113  17   0.0
Crop_45    32.8  16.4   41.8   8.7  42.0  17.3  1123  100   95    0  17   0.0
Crop_174  146.0  25.0   53.0  22.0  28.0   5.0   476  104  123   55  41  13.0

In [13]:
engine = create_engine(
    "postgresql://postgres:postgress@127.0.0.1:5432/postgres"
)

In [14]:
nutritient_df.to_sql("crop_nutritions", engine)

4

### fertilizers

In [15]:
fertlizers = pd.read_csv("./data_1/Fertilizers_data/Fertilizers_table.csv")

In [16]:
fertlizers.columns

Index(['Назва продукту', 'Серія', 'Тип внесення', 'N %', 'NO3 %', 'NH4 %',
       'P2O5 %', 'K2O %', 'Ca %', 'CaO %', 'Mg %', 'MgO %', 'S %', 'SO3 %',
       'B %', 'Cu %', 'Fe %', 'Mn %', 'Mo %', 'Zn %'],
      dtype='object')

In [29]:
fertlizers_ = fertlizers.rename(
    columns={
        'Назва продукту' : "product_name", 
        "Серія" : "product_line",
        'Тип внесення' : "application_method",
    }
)

fertlizers_["application_method"] = fertlizers_["application_method"].replace(
    {
        "Ґрунтове" : "Soil",
        "Ґрунтове / захищений ґрунт" : " Soil / protected soil",
        "Позакореневе (г/л)" : "Foliar (g/L)", 
        "Обробка насіння (г/л)" : "Seed treatment (g/L)", 
        "Водорозчинне / Краплинне" : "Water-soluble / Drip irrigation",
        "Водорозчинне" : "Water-soluble",
        "Краплинне / Фертигація" : "Drip irrigation / Fertigation",
    }
)

fertlizers_

,product_name,product_line,application_method,N %,NO3 %,NH4 %,P2O5 %,K2O %,Ca %,CaO %,Mg %,MgO %,S %,SO3 %,B %,Cu %,Fe %,Mn %,Mo %,Zn %
0,YaraVera AMIDAS,YaraVera,Soil,40.8,5.5,35.0,NaN,NaN,NaN,NaN,NaN,NaN,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,YaraBela SULFAN,YaraBela,Soil,24.0,12.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN
2,YaraBela EXTRAN,YaraBela,Soil,33.5,16.9,16.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YaraBela NITROMAG,YaraBela,Soil,27.0,13.5,13.5,NaN,NaN,7.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YaraMila COMPLEX 12-11-18,YaraMila,Soil,12.0,5.0,7.0,11.0,18.0,NaN,2.7,NaN,1.6,8.0,20.0,0.015,0.20,NaN,0.020,NaN,0.020
5,YaraMila CROPCARE 11-11-21,YaraMila,Soil,11.0,4.4,6.6,10.5,21.2,NaN,2.6,NaN,1.6,10.0,25.0,0.050,0.03,0.08,0.250,0.002,0.040
6,YaraMila NPK 7-20-28,YaraMila,Soil,7.0,0.9,6.1,20.0,28.0,NaN,2.0,NaN,1.2,3.0,7.5,0.020,NaN,0.10,0.030,NaN,NaN
7,YaraMila NPK 8-24-24,YaraMila,Soil,8.0,0.8,7.2,24.0,24.0,NaN,5.0,NaN,NaN,NaN,NaN,0.010,NaN,0.10,0.010,NaN,0.010
8,YaraMila NPK 9-12-25,YaraMila,Soil,9.0,2.6,6.4,12.0,25.0,NaN,2.0,NaN,1.2,2.6,6.5,0.020,NaN,NaN,NaN,NaN,NaN
9,YaraMila NPK 12-24-12,YaraMila,Soil,12.0,3.1,8.9,24.0,12.0,NaN,2.0,NaN,1.2,2.0,5.0,NaN,0.20,NaN,NaN,0.007,NaN
10,YaraMila NPK 16-27-7,YaraMila,Soil,16.0,4.2,11.8,27.0,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.10,NaN,NaN,NaN
11,YaraMila NPK 16-16-16,YaraMila,Soil,16.0,6.5,9.5,16.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,YaraLiva NITRABOR,YaraLiva,Soil / protected soil,15.4,14.1,1.3,NaN,NaN,18.3,NaN,25.6,NaN,NaN,NaN,0.300,NaN,NaN,NaN,NaN,NaN
13,YaraVita GRAMITREL,YaraVita,Foliar (g/L),NaN,NaN,64.0,NaN,150.0,NaN,250.0,NaN,50.0,NaN,150.0,NaN,NaN,NaN,NaN,NaN,80.000
14,YaraVita BRASSITREL PRO,YaraVita,Foliar (g/L),NaN,NaN,69.0,NaN,69.0,NaN,89.0,NaN,125.0,NaN,70.0,NaN,60.00,NaN,70.000,4.000,NaN
15,YaraVita MAIZE BOOST,YaraVita,Foliar (g/L),NaN,NaN,NaN,NaN,440.0,NaN,75.0,NaN,40.0,NaN,67.0,NaN,NaN,NaN,NaN,46.000,NaN
16,YaraVita MANCOZIN,YaraVita,Foliar (g/L),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,330.000,84.000
17,YaraVita KOMBIPHOS,YaraVita,Foliar (g/L),NaN,NaN,NaN,NaN,440.0,NaN,75.0,NaN,40.0,NaN,67.0,NaN,NaN,NaN,NaN,10.000,5.000
18,YaraVita UNIVERSAL BIO,YaraVita,Foliar (g/L),NaN,NaN,100.0,NaN,100.0,NaN,40.0,NaN,70.0,NaN,NaN,0.200,1.00,1.30,0.030,NaN,0.700
19,YaraVita BORTRAC 150,YaraVita,Foliar (g/L),NaN,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,YaraVita ZINTRAC 700,YaraVita,Foliar (g/L),NaN,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,700.000
21,YaraVita THIOTRAC 300,YaraVita,Foliar (g/L),NaN,NaN,200.0,NaN,NaN,NaN,NaN,NaN,NaN,300.0,750.0,NaN,NaN,NaN,NaN,NaN,NaN
22,YaraVita MANTRAC PRO,YaraVita,Foliar (g/L),NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.000,NaN,NaN
23,YaraVita MOLYTRAC 250,YaraVita,Foliar (g/L),NaN,NaN,250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.000,NaN
24,YaraVita TEPROSYN NP+Zn,YaraVita TEPROSYN,Seed treatment (g/L),147.0,NaN,NaN,243.0,291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,YaraTera CALCINIT,YaraTera,Water-soluble / Drip irrigation,15.5,14.4,1.1,NaN,NaN,19.0,NaN,26.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,YaraTera KRISTALON Жовтий (13-40-13),YaraTera,Water-soluble,13.0,4.4,8.6,40.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
27,YaraTera KRISTALON Блакитний (17-6-18),YaraTera,Water-soluble,17.0,8.0,9.0,6.0,18.0,NaN,20.0,NaN,8.0,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
28,YaraTera KRISTALON Білий (13-5-26),YaraTera,Water-soluble,13.0,7.0,6.0,5.0,26.0,NaN,22.5,NaN,9.0,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
29,YaraTera KRISTALON Червоний (12-12-36),YaraTera,Water-soluble,12.0,10.1,1.9,12.0,36.0,NaN,2.5,NaN,1.0,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
30,YaraTera KRISTALON SPECIAL (18-18-18),YaraTera,Water-soluble,18.0,4.9,3.3,18.0,18.0,NaN,5.0,NaN,2.0,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
31,YaraTera KRISTALON SPECIAL PLUS (20-20-20),YaraTera,Water-soluble,20.0,3.1,2.3,20.0,20.0,NaN,4.0,NaN,NaN,NaN,NaN,0.025,0.01,0.07,0.040,0.004,0.025
32,YaraTera KRISTA K PLUS,YaraTera,Water-soluble,NaN,NaN,NaN,NaN,46.3,NaN,NaN,NaN,13.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,YaraTera KRISTA MAG,YaraTera,Water-soluble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,YaraTera KRISTA MAP,YaraTera,Water-soluble,12.0,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,YaraTera KRISTA MKP,YaraTera,Water-soluble,NaN,NaN,NaN,52.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,YaraTera KRISTA SOP,YaraTera,Water-soluble,NaN,NaN,NaN,NaN,52.0,NaN,NaN,NaN,18.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,FOLICARE 10-5-40,FOLICARE,Water-soluble,10.0,9.4,0.2,5.0,40.0,NaN,10.2,NaN,0.9,4.0,NaN,0.020,0.10,0.20,0.100,0.010,0.020
38,FOLICARE 18-18-18,FOLICARE,Water-soluble,18.0,5.3,4.8,18.0,18.0,NaN,7.3,NaN,0.9,2.9,NaN,0.020,0.10,0.20,0.100,0.010,0.020
39,FERTICARE HYDRO 6-14-30,FERTICARE,Drip irrigation / Fertigation,6.0,6.0,NaN,13.7,30.1,NaN,9.2,NaN,2.6,3.7,NaN,0.030,0.02,0.20,0.140,0.004,0.020
40,FERTICARE TOMATO 3-10-30,FERTICARE,Drip irrigation / Fertigation,3.0,3.0,NaN,10.0,30.0,NaN,28.0,NaN,4.8,11.2,NaN,0.020,NaN,0.14,0.030,0.003,0.020
41,FERTICARE KOMBI 14-11-25,FERTICARE,Drip irrigation / Fertigation,14.0,6.0,2.8,11.5,25.3,NaN,14.0,NaN,1.4,5.6,NaN,0.020,0.01,0.10,0.100,0.002,0.010
42,FERTICARE VEGETABLES 7-10-30,FERTICARE,Drip irrigation / Fertigation,7.0,7.0,NaN,10.0,30.0,NaN,14.0,NaN,4.2,5.6,NaN,0.020,NaN,0.14,0.033,0.003,0.020

In [31]:
fertlizers_.to_sql("fertilizers_table", engine)

43